### ISSUE TITLE
Make use GPUArrays interface

### ISSUE THREAD

**Issue by Roger-luo** [QuantumBFS/CuYao.jl#10]
The kernel codes should be similar, but `GPUArrays` contains a fake GPU Array that can run on CPU which make it easier to test and it would just work on AMD GPUs (e.g for MacOS)

**Comment by GiggleLiu** [comment]
What is the point of using GPUArrays? Why do we support AMD card with 'Cu'Yao?

**Comment by Roger-luo** [comment]
It's not a big deal, the code is exactly the same. They have similar interface, it's easier to test for me if it supports GPUArray. There's not much effort needed to apply this change, I mean why not.

**Comment by GiggleLiu** [comment]
We use `@cuda` in the implementations, we need a lot extra code to support GPUArrays.

Maybe I misunderstood your point?

**Comment by Roger-luo** [comment]
I mean the code inside `@cuda` is exact the same. So no big change.
