### ISSUE TITLE
Use GPUfy loops to avoid type piracy and compatibility issue

### ISSUE THREAD

**Issue by Roger-luo** [QuantumBFS/CuYao.jl#11]
https://github.com/QuantumBFS/CuYao.jl/blob/62737258d4c630a81b2679cfbb30f396935105fa/src/CUDApatch.jl#L28

**Comment by Roger-luo** [comment]
I'll use GPUifyingLoops instead 

Ref: https://github.com/JuliaGPU/CUDAnative.jl/pull/432

**Comment by GiggleLiu** [comment]
close because we do not need hack `pow` anymore.
