### ISSUE TITLE
Implement in-place kron and batched_kron

### ISSUE THREAD

**Issue by elisno** [QuantumBFS/CuYao.jl#53]
Wouldn't it be enough define 

```julia
function kron!(C::CuArray{T3}, A::Union{CuArray{T1}, Adjoint{<:Any, <:CuArray{T1}}}, B::Union{CuArray{T2}, Adjoint{<:Any, <:CuArray{T2}}}) where {T1, T2, T3} 
```
by reusing the out-of-place version

https://github.com/QuantumBFS/CuYao.jl/blob/ba08a02477fe8115959c5759f8ceb5767f48248e/src/CUDApatch.jl#L76-L91

but replace `res` with `C` and adding some bounds checks etc.?

Would the samee apply to `batched_kron!`?

**Comment by Roger-luo** [comment]
yes, please feel free to open a PR, I could help you finish it. but probably better to use `KernelAbstraction` or `GPUArrays` to write this now, since this is not CUDA specific anyways.

**Comment by Roger-luo** [comment]
Update: I think it's probably better to move things to LuxurySparse instead of here so you guys won't need to depend on a very heavy dependency. See https://github.com/MichielStock/Kronecker.jl/issues/61#issuecomment-626252485 also

**Comment by GiggleLiu** [comment]
`KernelAbstractions` is very good in many cases, but I find it does not alway have a better performance. Need some benchmark before switching to it.

@Roger-luo I don't think it is good to put GPU code in LuxurySparse though. Maybe we need a new package later. But currently, there are two options

* CuArrays
* CuYao

**Comment by elisno** [comment]
I could start with a PR here for `CuArray`. But the goal is to have similar functions for `CuSparseMatrixCSC`.
Once `kron!` is a part of Base, it would be more consistent have `kron!(C::CuArray,...)` is a part of CuArrays.jl.

It would make sense to keep the remaining functions (GPU-agnostic versions of `kron!` and `batched_kron!`) would be a part of the Yao suite.

I haven't used KernelAbstractions before, but that might be a fun exercise.
