### ISSUE TITLE
Not registered in the new registry?

### ISSUE THREAD

**Issue by Moelf** [QuantumBFS/CuYao.jl#6]

**Comment by GiggleLiu** [comment]
Should have been registered, but haven't figured out how to get the GPU test work.

@Roger-luo Do you have time to get it registered in next a few day?

**Comment by Roger-luo** [comment]
No, this is not registered yet. I could register this this weekend when I'm back to office. But I want to fix the CI before we tag the first version, or so we could guarantee everything is fine at least for our current tests. And the `Project.toml` and `Manifest.toml` need some polish as well.

**Comment by Roger-luo** [comment]
registered and CI is on. Not sure why cov is not shown correctly tho. But I think this issue is resolved, thanks!
