### ISSUE TITLE
supports cu(hamiltonian)

### ISSUE THREAD

**Issue by ywlds** [QuantumBFS/CuYao.jl#71]
current it seems the cu(state) is ok, but when we want to utilize expect(hamiltonian, cu(reg))
seems the hamilitonian is not supported by the current cu  function.

can we add this function to fully use the gpu power for some case, that we need expectation value?

Many thanks,

**Comment by GiggleLiu** [comment]
What is your hamiltonian like? This expression will just work for most hamiltonians.

**Comment by ywlds** [comment]
expect(cu(hamiltonian), cu(reg)), the hamiltonian would be a molecule hamiltonian composed of a lot of Pauli terms

**Comment by ywlds** [comment]
> What is your hamiltonian like? This expression will just work for most hamiltonians.

expect(cu(hamiltonian), cu(reg)), the hamiltonian would be a molecule hamiltonian composed of a lot of Pauli terms

**Comment by GiggleLiu** [comment]
You can not and do not need to do this
```julia
cu(hamiltonian)
```

hamiltonian is a circuit representation, not something can be uploaded to GPU.
