### ISSUE TITLE
Incorrect overloading of math functions

### ISSUE THREAD

**Issue by Roger-luo** [QuantumBFS/CuYao.jl#8]
https://github.com/QuantumBFS/CuYao.jl/blob/ac4d15856a90bd8a63b3fdc4a8711f98af0dac49/src/CUDApatch.jl#L19

This will cause the CPU version dispatch to wrong place, since it overloads the `angle` in `Base` instead of `CUDAnative`

**Comment by GiggleLiu** [comment]
Do you mean the CUDAnative exports angle in Base, and here we should use another name? Then I will be ok with this change

**Comment by Roger-luo** [comment]
Yes this will cause program fails on CPU. Should be resolved in future with Cassette in future version of CuArrays, but I'll use a new name for now. I'll PR later.
